### ISSUE TITLE
[FEAT]: Carousel Addition

### ISSUE THREAD

**Issue by Anushka-Bhowmick** [Anushka-Bhowmick/Supnits-Classes#1]
Add a carousel where we can include sliding images for the website.
Something like this below : 
![Screenshot (463)](https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/76967222/f25d426c-ad58-485d-92d4-055cf690935c)

- [ ]  Get yourself assigned before working on the issue.
- [ ] Follow the Contribution Guidelines properly for contribution

**Comment by MAVRICK-1** [comment]
Can you assign me this?

**Comment by Anushka-Bhowmick** [comment]
> Can you assign me this?

Ofcourse! I can assign you but on 3rd JAN as the coding period begins then

**Comment by rko0211** [comment]
Can you assign me this task I am willing to contribute in this under apertre 24.thank you

**Comment by AnitSarkar123** [comment]
Assign me under Apertre'24

**Comment by MAVRICK-1** [comment]
@Anushka-Bhowmick  Could you please assign this task to someone else, I have urgent work that has just come up

**Comment by Anushka-Bhowmick** [comment]
> Can you assign me this task I am willing to contribute in this under apertre 24.thank you

I am assigning you for this issue
