### ISSUE TITLE
Social media icons

### ISSUE THREAD

**Issue by madhurima316** [Anushka-Bhowmick/Supnits-Classes#10]
The social media icons are opening up to home page instead of the specific channels and accounts for the testimonials - students , tutors and even for "Supnits -Classes " official pages. Please assign me this issue

**Comment by Anushka-Bhowmick** [comment]
> The social media icons are opening up to home page instead of the specific channels and accounts for the testimonials - students , tutors and even for "Supnits -Classes " official pages. Please assign me this issue

I'll do that part later as I can't provide you the personal links now. Hence, i am closing this issue :)
