### ISSUE TITLE
[FEAT]: Fixing a Quick link and adding a hover effect on the links

### ISSUE THREAD

**Issue by madhurima316** [Anushka-Bhowmick/Supnits-Classes#11]
In the footer section of the webpage , in the "useful links" sections , the mentioned sections can not be accessed or navigated from  there . I am willing to make that part navigable , please assign me this issue .

**Comment by Anushka-Bhowmick** [comment]
> In the footer section of the webpage , in the "useful links" sections , the mentioned sections can not be accessed or navigated from there . I am willing to make that part navigable , please assign me this issue .

I have checked and all the useful links are working fine. Only the "Home" in the Quick Links seem to have an error!
Fix that part and create a hover on the links.

**Comment by madhurima316** [comment]
okay , thank you

**Comment by madhurima316** [comment]
okay, thank you

**Comment by madhurima316** [comment]
https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/145414858/7a68dd3a-6bb0-4159-a7a3-d89ca4e1a78a

Can you please check the video once because the useful links are not working here and the home link is working properly for me.

**Comment by Anushka-Bhowmick** [comment]
> WhatsApp.Video.2024-01-03.at.6.28.17.PM.mp4 
> Can you please check the video once because the useful links are not working here and the home link is working properly for me.


https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/76967222/cbef6790-f055-4f52-a4b5-ff5a3feded50

I have checked. It seems to be working fine!

**Comment by Anushka-Bhowmick** [comment]
alright! got it! When you are in the homepage, the links appear to be working fine but it's not working when you are in a different section.
You can fix that. I'll increase the alloted points. @madhurima316

**Comment by madhurima316** [comment]
okay

**Comment by madhurima316** [comment]
would you please make the update else I would have just 1 day to complete it.

**Comment by Anushka-Bhowmick** [comment]
> would you please make the update else I would have just 1 day to complete it.

Sure! And make sure to git pull before sending a PR.

**Comment by madhurima316** [comment]
https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/145414858/e90c9154-e8d4-4d6d-b330-b0dc205061c4

I am unable to open the code in chrome . So it may take some more time, can you please extend the duration till tomorrow.

**Comment by Anushka-Bhowmick** [comment]
> supnit.srv.mp4 
> I am unable to open the code in chrome . So it may take some more time, can you please extend the duration till tomorrow.

come on discord tomorrow and ping me. I'll help you set it up

**Comment by madhurima316** [comment]
okay
