### ISSUE TITLE
"our materials " section is not active

### ISSUE THREAD

**Issue by madhurima316** [Anushka-Bhowmick/Supnits-Classes#12]
In the Home page , in the "our materials " section, the materials aren't opening up upon clicking the subjects and the subjects aren't clickable too . Please assign me the issue.

**Comment by Anushka-Bhowmick** [comment]
> In the Home page , in the "our materials " section, the materials aren't opening up upon clicking the subjects and the subjects aren't clickable too . Please assign me the issue.

The materials will be added later. It is not a part of contribution!
You'll be assigned in the other issue :)
