### ISSUE TITLE
[FEAT]: Make the Statistics portion dynamic

### ISSUE THREAD

**Issue by Anushka-Bhowmick** [Anushka-Bhowmick/Supnits-Classes#14]
![Screenshot (496)](https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/76967222/5a2ca229-b37b-476f-8948-e6666050b2f3)

Presently this portion is static. Please make it dynamic like the numbers would be loading on scroll.

**Comment by rko0211** [comment]
i can try to solve this issue kindly assign me this one under apertre24 thank you.

**Comment by Anushka-Bhowmick** [comment]
> i can try to solve this issue kindly assign me this one under apertre24 thank you.

you have already been assigned for a previous issue #1 !
Please complete the task before I assign you a new one.

**Comment by callmeVineeth** [comment]
I'm also available to handle this task in case it hasn't been assigned yet; feel free to assign it to me.

**Comment by Anushka-Bhowmick** [comment]
> I'm also available to handle this task in case it hasn't been assigned yet; feel free to assign it to me.

sorry! I won't be able to assign this issue to you if u aren't a participant in apertre

**Comment by callmeVineeth** [comment]
ok

**Comment by Souvik34** [comment]
Please assign me the task
