### ISSUE TITLE
[FEAT]: Dark/Light mode

### ISSUE THREAD

**Issue by Anushka-Bhowmick** [Anushka-Bhowmick/Supnits-Classes#2]
Add a dark and light mode for the website

- [ ]  Get yourself assigned before working on the issue.
- [ ] Follow the Contribution Guidelines properly for contribution

**Comment by rko0211** [comment]
I would like to contribute in this project under Apertre24 so kindly assign me this issue. Thank you

**Comment by Anushka-Bhowmick** [comment]
> I would like to contribute in this project under Apertre24 so kindly assign me this issue. Thank you

Sure! I'll assign you this issue on 3rd January.

**Comment by ANAMASGARD** [comment]
Ma'am I know you people who are much more experienced are willing to solve in issue , but I just want one chance from you to allow me add Dark/Light Mode , trust me i won't disappoint you .
Happy New Year (you can make my New Year very Special by giving one chance please )

**Comment by Anushka-Bhowmick** [comment]
> Ma'am I know people who are much more experienced are willing to solve in issue , but I just want one chance from you to allow me add Dark/Light Mode , trust me i won't disappoint you .
> Happy New Year (you can make my New Year very Special by giving one chance please )

I would love to give you a chance but since @rko0211 has said it first, let's give him a chance to do it. If he is unable to, you'll be given next. In the meanwhile you can raise further issues and suggest any changes u want😊
Happy New Year!

**Comment by Anushka-Bhowmick** [comment]
> Ma'am I know people who are much more experienced are willing to solve in issue , but I just want one chance from you to allow me add Dark/Light Mode , trust me i won't disappoint you . Happy New Year (you can make my New Year very Special by giving one chance please )

I am assigning you for this issue :)

**Comment by madhurima316** [comment]
I want to contribute too.

**Comment by Anushka-Bhowmick** [comment]
> I want to contribute too.

You are already assigned for this issue #11 :)

**Comment by ANAMASGARD** [comment]
Thank you Ma'am for assigning this issue to me I just wanted to ask is their any time limit before which i should submit PR.

**Comment by ANAMASGARD** [comment]
And ma'am also wanted to ask what is the meaning of points 10 badge on this !

**Comment by Anushka-Bhowmick** [comment]
> Thank you Ma'am for assigning this issue to me I just wanted to ask is their any time limit before which i should submit PR.

Yes, since it's labelled as medium, the time limit is 2 days.

**Comment by Anushka-Bhowmick** [comment]
> And ma'am also wanted to ask what is the meaning of points 10 badge on this !

Medium issues carry 10 points for apertre which will be counted on the leaderboard.

**Comment by ANAMASGARD** [comment]
OK , THANKS , ma'am i just wanted to ask that the dark / light theme toggle button i should be adding to the right hand side of next to the CONTACT menu 
IN THE NAVBAR.CSS FILE IN THE CODE .
please reply

**Comment by Anushka-Bhowmick** [comment]
> OK , THANKS , ma'am i just wanted to ask that the dark / light theme toggle button i should be adding to the right hand side of next to the CONTACT menu IN THE NAVBAR.CSS FILE IN THE CODE . please reply

yes perfect and try to maintain the color code of the website in the icon.

**Comment by ANAMASGARD** [comment]
Ma'am I wanted to ask that i don't know that if i will make changes for the desktop version of the website how well if will scale with the mobile form of website .
(https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/137998824/459f36b4-7af9-4479-95df-ea9c387385e5)

**Comment by Anushka-Bhowmick** [comment]
> Ma'am I wanted to ask that i don't know that if i will make changes for the desktop version of the website how well if will scale with the mobile form of website . (https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/137998824/459f36b4-7af9-4479-95df-ea9c387385e5) This is the toggle button i will add to the website .

make it for desktop and try to maintain the responsiveness.

**Comment by ANAMASGARD** [comment]
try to maintain the responsiveness. can you please elaborate on what you expect me to do ??

**Comment by Anushka-Bhowmick** [comment]
> try to maintain the responsiveness. can you please elaborate on what you expect me to do ??

the size of the toggle button should scale up and down as per the screen size

**Comment by ANAMASGARD** [comment]
you mean when a user switches from the desktop version of website to mobile version correct.

**Comment by Anushka-Bhowmick** [comment]
> you mean when a user switches from the desktop version of website to mobile version correct.

yes!

**Comment by ANAMASGARD** [comment]
Ma'am I am unable to add the toggle button to the project when i am clicking on server live of index.html it is showing me a blank page .

**Comment by rko0211** [comment]
> Ma'am I am unable to add the toggle button to the project when i am clicking on server live of index.html it is showing me a blank page .

Actually friend it is a React application not just using Html, Css, Js. For that you have to install npm in the system and some more thing.

**Comment by Anushka-Bhowmick** [comment]
> Ma'am I am unable to add the toggle button to the project when i am clicking on server live of index.html it is showing me a blank page .
> 

Yes in the terminal run the following commands.
1. npm install
2. npm start

**Comment by ANAMASGARD** [comment]
I have installed both npm and npx to latest version but it is still not working

**Comment by ANAMASGARD** [comment]
Ma'am I want to contribute but I am unable to figure out should I write toggle button code in Navbar.css or add it on style.css so that it is applied across web .

**Comment by Anushka-Bhowmick** [comment]
> Ma'am I want to contribute but I am unable to figure out should I write toggle button code in Navbar.css or add it on style.css so that it is applied across web .

in the navbar

**Comment by Soumojitshome2023** [comment]
Assign me this issue. I want to work on it.
Thank You.
[Soumojit Shome](https://www.soumojitshome.me/)

**Comment by Souvik34** [comment]
Assign me this task. I want to contribute

**Comment by Anushka-Bhowmick** [comment]
> Assign me this task. I want to contribute

@Soumojitshome2023 since it's been 3 days since I assigned the issue, I'll assign it to @Souvik34 next.

**Comment by Sneha123-zudo** [comment]
PLease assign me this issue
