### ISSUE TITLE
Adding various micro-animation which changes with mouse in Hero,Materials and subscription component. 

### ISSUE THREAD

**Issue by ASHISH26940** [Anushka-Bhowmick/Supnits-Classes#22]
https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/116710038/0b876e2f-6a66-46a3-82f4-3149b56e82c2

**Comment by Anushka-Bhowmick** [comment]
> WhatsApp.Video.2024-01-05.at.20.40.04_1e0d498d.mp4

just check someone is working on the materials portion in issue #19 . 
Apart from that, you can work on the micro animations in the remaining sections.
