### ISSUE TITLE
[FEAT]: Addition of a logo (favicon)

### ISSUE THREAD

**Issue by Debaditya-Som** [Anushka-Bhowmick/Supnits-Classes#3]
Currently, our website lacks a favicon. A favcion would enhance the branding of the website

**Comment by IndraniSom** [comment]
assign me in this issue under Apertre-24 :)

**Comment by Anushka-Bhowmick** [comment]
> assign me in this issue under Apertre-24 :)

i guess @Debaditya-Som is willing to work on it. So he'll be assigned for this :)

**Comment by IndraniSom** [comment]
O ouk sure :)

**Comment by AnitSarkar123** [comment]
@Anushka-Bhowmick can you assign me this issue under Aperture'24 because it is more than one day but @Debaditya-Som don't solve it.

**Comment by Anushka-Bhowmick** [comment]
> @Anushka-Bhowmick can you assign me this issue under Aperture'24 because it is more than one day but @Debaditya-Som don't solve it.

I'll ask the next person in queue. If she is not willing to, you'll be assigned next

**Comment by AnitSarkar123** [comment]
But she is assigned in another issue
