### ISSUE TITLE
Improve Visibility of Homepage Slider Text in Supnits-Classes Website

### ISSUE THREAD

**Issue by Soumojitshome2023** [Anushka-Bhowmick/Supnits-Classes#33]
## Problem:
The text in the homepage slider of the Supnits-Classes website is currently not clearly visible, potentially affecting the user experience and readability.

## Expected Behavior:
The text in the homepage slider should have sufficient contrast and visibility against the background, ensuring a clear and aesthetically pleasing presentation.

##Steps to Reproduce:
1. Visit the Supnits-Classes website.
2. Observe the text in the homepage slider, paying attention to its visibility.

## Current Behavior:
The text in the homepage slider is not adequately visible, which may lead to difficulties in reading and understanding the displayed content.

## Screenshot
![image](https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/121761154/eb7bcbb9-f870-48f8-9bb4-97d28a4ab9df)

**Comment by Soumojitshome2023** [comment]
Please assign me this issue . I want to work on it. Thank You.

**Comment by Anushka-Bhowmick** [comment]
> Please assign me this issue . I want to work on it. Thank You.

cool! here u go!
