### ISSUE TITLE
Implement Dark Mode Option on Supnits-Classes Website

### ISSUE THREAD

**Issue by Soumojitshome2023** [Anushka-Bhowmick/Supnits-Classes#35]
## Problem:
The Supnits-Classes website currently does not offer a dark mode option, limiting user accessibility and customization preferences.

## Expected Behavior:
The website should include a dark mode option, allowing users to toggle between light and dark themes for improved visibility and reduced eye strain.

## Features Requested:
1. Dark Mode Toggle: Implement a toggle switch or button that allows users to switch between light and dark modes.
2. User Preference Storage: If possible, enable the website to remember the user's dark mode preference for future visits.

## Steps to Reproduce:
1. Visit the Supnits-Classes website.
2. Observe the absence of a dark mode option.

## Current Behavior:
The website does not provide a dark mode option, limiting user customization and potentially causing discomfort during extended usage.

### Assign me this issue. I want to work on it.
Thank You. 
[Soumojit Shome](https://www.soumojitshome.me/)

**Comment by Anushka-Bhowmick** [comment]
there is already an existing issue #2 . I'll assign you there.

**Comment by Soumojitshome2023** [comment]
ok
