### ISSUE TITLE
Adding transitions to the stats

### ISSUE THREAD

**Issue by Souvik34** [Anushka-Bhowmick/Supnits-Classes#36]
The numeric counts animation from 0 to the desired number will be implemented in the stats

**Comment by Anushka-Bhowmick** [comment]
there is an existing issue #14 . I'll assign u there.

**Comment by Souvik34** [comment]
Sure

**Comment by Anushka-Bhowmick** [comment]
> Sure

please comment under issue #14 . Then I'll be able to assign you
