### ISSUE TITLE
Custom scroll bar

### ISSUE THREAD

**Issue by Souvik34** [Anushka-Bhowmick/Supnits-Classes#40]
There will be a  custom scroll bar added

**Comment by Anushka-Bhowmick** [comment]
> There will be a custom scroll bar added

can you please write in details. Where will u add this?

**Comment by Souvik34** [comment]
In the main website

**Comment by Souvik34** [comment]
Will replace the default one with the custom one with the matching colour theme of the website

**Comment by Anushka-Bhowmick** [comment]
> Will replace the default one with the custom one with the matching colour theme of the website

I mean what do you want to change?

**Comment by Souvik34** [comment]
the scroll bar 
<img width="52" alt="image" src="https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/98397984/c49c2d2f-06e7-4ace-8c67-f7e743dd56ef">
I will change this

**Comment by Souvik34** [comment]
I will add a custom one with the matching theme color. The functionality and other details of the website will be same

**Comment by Anushka-Bhowmick** [comment]
> I will add a custom one with the matching theme color. The functionality and other details of the website will be same, there will be no change in that

alright, the color change
