### ISSUE TITLE
Placeholder Content in Blog Section

### ISSUE THREAD

**Issue by abhraneel2004** [Anushka-Bhowmick/Supnits-Classes#42]
I came across your website and noticed that the blog section appears to have placeholder content. As a user, I believe that having meaningful and relevant content in the blog section would enhance the overall user experience and provide valuable information to visitors.

If this is intentional or if you are still working on adding content, please disregard this message. However, if you are open to contributions or if there's anything I can do to help, I would be more than happy to assist.

Thank you for your time, and I appreciate the effort you've put into your website!

I want to contribute under **Apertre** contest.

**Comment by Anushka-Bhowmick** [comment]
> I came across your website and noticed that the blog section appears to have placeholder content. As a user, I believe that having meaningful and relevant content in the blog section would enhance the overall user experience and provide valuable information to visitors.
> 
> If this is intentional or if you are still working on adding content, please disregard this message. However, if you are open to contributions or if there's anything I can do to help, I would be more than happy to assist.
> 
> Thank you for your time, and I appreciate the effort you've put into your website!
> 
> I want to contribute under **Apertre** contest.

Actually I'll add the additional informations later. They are left to be edited.
However if you want to work on the light/dark issue #2 , please drop a comment below that issue and I'll assign it to you! :)

**Comment by abhraneel2004** [comment]
Actually, I don't know react. So I can not work on that issue. Anyways, your project looks good.
