### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by arghadipmanna101** [Anushka-Bhowmick/Supnits-Classes#44]
- Will add contributors name in Readme file.
- will stylize the readme
- will add photos
- will add gif

**Comment by arghadipmanna101** [comment]
please assign me under Apertre

**Comment by Anushka-Bhowmick** [comment]
> * Will add contributors name in Readme file.
> * will stylize the readme
> * will add photos
> * will add gif

I want a specific change to be made. Please add a point after git clone on how to run the code in local:
We need to run 2 commands in the terminal
1. npm install
2. npm start
just make this change

**Comment by arghadipmanna101** [comment]
ok
