### ISSUE TITLE
[BUG]: images are not visible

### ISSUE THREAD

**Issue by Anushka-Bhowmick** [Anushka-Bhowmick/Supnits-Classes#5]
![Screenshot (501)](https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/76967222/e4c8427c-0b91-4142-a176-04f4dc9afc9e)

In few sections, the images are not visible.

Steps to reproduce:
There is a specific error in the Teachers.js and Tes.js in the image parameter names.
Fix the code!

**Comment by callmeVineeth** [comment]
I would work with the image  loading problem, finds  images in the multiple pages are  not loading
.
.
![Screenshot (192)](https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/130293688/6768bef0-91dc-4b85-9028-24253f3a32e2)
![Screenshot (191)](https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/130293688/ecb8dad0-c709-433d-b252-92833d9ff949)

**Comment by rko0211** [comment]
Hello, I want to work in this issue kindly assign me this under apertre24. Thank you

**Comment by Anushka-Bhowmick** [comment]
@rko0211 as you'll be assigned in another issue as mentioned earlier, let @callmeVineeth be given a chance :)

**Comment by callmeVineeth** [comment]
I already fixed the image  loading issues, may I create a pull  request
.
.
![Screenshot (195)](https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/130293688/f71f3ebc-5a6d-40d0-9565-a9cd0edb5125)
![Screenshot (196)](https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/130293688/5d589837-f2a3-4075-a90a-56d9cf191123)

**Comment by callmeVineeth** [comment]
Thankyou for giving me the chance

**Comment by Anushka-Bhowmick** [comment]
> Thankyou for giving me the chance

Great work! As the event starts from 3rd January, please open the PR tonight after i assign you :)

**Comment by callmeVineeth** [comment]
Thank you

**Comment by Anushka-Bhowmick** [comment]
@callmeVineeth check the testimonials section as well! and create further pull requests only when I assign you! If you create PR before the coding period it won't be accepted

**Comment by callmeVineeth** [comment]
Sorry for the early request it was a mistake from my part, I don't  create  further  requests before  assigning the task.

**Comment by callmeVineeth** [comment]
I  accidentally unassigned the issue, can you please reassign the issue

**Comment by Anushka-Bhowmick** [comment]
@callmeVineeth please fix the bug in the Tes.js file(Testimonials) as well. Then your PR will be merged :)

**Comment by callmeVineeth** [comment]
ok

**Comment by Anushka-Bhowmick** [comment]
> ok

@callmeVineeth great! your PR has been merged 🎉
You received 5 points for apertre :)

**Comment by callmeVineeth** [comment]
Thanks for the review and merging
