### ISSUE TITLE
[FEAT]: Changes in the Styling

### ISSUE THREAD

**Issue by Anushka-Bhowmick** [Anushka-Bhowmick/Supnits-Classes#6]
Change the hover on the Navbar from this:

![Screenshot (504)](https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/76967222/5c29efb1-47aa-4cfb-b1e1-85d21b0e79c3)

to this:

![Screenshot (503)](https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/76967222/e97ecd1c-edde-4a46-a173-15c996cb7258)

**Comment by callmeVineeth** [comment]
I would like to work on the Navbar hovering issue.

**Comment by Anushka-Bhowmick** [comment]
> I would like to work on the Navbar hovering issue.

cool! I'll assign you tonight :)

**Comment by rko0211** [comment]
I would like to contribute in this issue kindly assign me this task

**Comment by callmeVineeth** [comment]
![Screenshot (195)](https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/130293688/9c362951-6b61-4f3d-b31e-cb277088135e)
![Screenshot (196)](https://github.com/Anushka-Bhowmick/Supnits-Classes/assets/130293688/0dcca756-54fd-48ac-8b4e-610e12ef62b8)


> > I would like to work on the Navbar hovering issue.
> 
> cool! I'll assign you tonight :)

Ok
