### ISSUE TITLE
[FEAT]: ADDING LOGIN AND SIGN UP PAGE (Frontend)

### ISSUE THREAD

**Issue by AnitSarkar123** [Anushka-Bhowmick/Supnits-Classes#8]
Assign me under Apertre'24

**Comment by Anushka-Bhowmick** [comment]
> Assign me under Apertre'24

1. First of all the login and signup page will come under one issue. So make these 2 issues into one.
2.  Secondly, please elaborate your approach, if you will add authentication or not.

**Comment by AnitSarkar123** [comment]
Yes, i want to add authentication.

**Comment by AnitSarkar123** [comment]
Can I use any ui library or only CSS ,HTML,SCSS

**Comment by Anushka-Bhowmick** [comment]
> Can I use any ui library or only CSS ,HTML,SCSS

Yes you can use UI Library

**Comment by Anushka-Bhowmick** [comment]
> Can I use any ui library or only CSS ,HTML,SCSS

You are not supposed to change the issue name by your own @AnitSarkar123

**Comment by AnitSarkar123** [comment]
Ok,i am said to you that I don't want to make the authentication page...but this time I forgot to change the issue name...can I change it to (frontend+back-end)....

**Comment by Anushka-Bhowmick** [comment]
> Ok,i am said to you that I don't want to make the authentication page...but this time I forgot to change the issue name...can I change it to (frontend+back-end)....

@AnitSarkar123 please clearly mention which part you are comfortable in...frontend/backend or both. Accordingly I'll assign you and allot the points

**Comment by AnitSarkar123** [comment]
Frontend part

**Comment by Anushka-Bhowmick** [comment]
> I am intrested in this issue.

alright! here you go!

**Comment by Sneha123-zudo** [comment]
Can i use plain html and css

**Comment by Anushka-Bhowmick** [comment]
> Can i use plain html and css ?

no, you have to use react as the project is based on it.

**Comment by Sneha123-zudo** [comment]
ok
